#!/bin/sh

# POST-COMMIT HOOK
#
# The post-commit hook is invoked after a commit. Subversion runs
# this hook by invoking a program (script, executable, binary,
# etc.) named `post-commit' (for which
# this file is a template) with the following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#
# Because the commit has already completed and cannot be undone,
# the exit code of the hook program is ignored.  The hook program
# can use the `svnlook' utility to help it examine the
# newly-committed tree.
#
# On a Unix system, the normal procedure is to have `post-commit'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that `post-commit' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# `post-commit.bat' or `post-commit.exe',
# but the basic idea is the same.
#  
# Here is an example hook script, for a Unix /bin/sh interpreter:

# 
SVN=/usr/local/svn-install/current/bin/svn
SVNLOOK=/usr/local/svn-install/current/bin/svnlook
SVNADMIN=/usr/local/svn-install/current/bin/svnadmin
MAILER=/root/bin/svn/svn-mailer
PUBSUB=/usr/local/svnpubsub/commit-hook.py
MASTER_HOSTNAME=eris.apache.org
HOSTNAME=`/bin/hostname`

REPOS="$1"
REV="$2"

# Deltify predecessors of things changed in this revision.
#nice -2 $SVNADMIN deltify "$REPOS" -r "$REV" &
#$SVNADMIN deltify "$REPOS" -r "$REV"
$SVNADMIN dump --incremental -r "$REV" "$REPOS" > /x1/svn/hot-backups/dist.$REV 2>>/var/log/svndump

# check if the hook is running on the master svn
if [ "$HOSTNAME" = "$MASTER_HOSTNAME" ] 
then
    # Send the commit mail
    $MAILER commit "$REPOS" "$REV" /x1/svn/asf-mailer-dist.conf \
        2>>/var/log/svnmailer/errors/mailer-stderr &
fi

#
if [ "$HOSTNAME" = "$MASTER_HOSTNAME" ] 
then
    export PYTHON_EGG_CACHE="/var/tmp/daemon_egg_cache"
    $PUBSUB "$REPOS" "$REV" >>/var/log/svn_pubsub.log 2>&1 &
fi

