#!/bin/sh

# POST-COMMIT HOOK
#
# The post-commit hook is invoked after a commit. Subversion runs
# this hook by invoking a program (script, executable, binary,
# etc.) named `post-commit' (for which
# this file is a template) with the following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#
# Because the commit has already completed and cannot be undone,
# the exit code of the hook program is ignored.  The hook program
# can use the `svnlook' utility to help it examine the
# newly-committed tree.
#
# On a Unix system, the normal procedure is to have `post-commit'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that `post-commit' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# `post-commit.bat' or `post-commit.exe',
# but the basic idea is the same.
#
# Here is an example hook script, for a Unix /bin/sh interpreter:

#
SVN=/usr/bin/svn
SVNLOOK=/usr/bin/svnlook
SVNADMIN=/usr/bin/svnadmin
SVNSYNC=/usr/bin/svnsync
#MAILER=/usr/local/svn-install/hooks/mailer.py
MAILER=/root/bin/svn/svn-mailer
SUDO=/usr/local/bin/sudo
SETLOCK=/root/bin/setlock.pl
MASTER_HOSTNAME=hades.apache.org
HOSTNAME=`/bin/hostname`
BUILDBOT=/x1/svn/hooks/svn_buildbot.py
BUILDBOT_PROJECT_PATHS=/x1/svn/hooks/buildbot_project_paths
PUBSUB=/opt/svnpubsub/commit-hook.py

#
REPOS="$1"
REV="$2"
shard=`expr $REV / 1000`

if [ "$HOSTNAME" = "$MASTER_HOSTNAME" ]
then
    # Deltify predecessors of things changed in this revision.
    #nice -2 $SVNADMIN deltify "$REPOS" -r "$REV" &
    #$SVNADMIN deltify "$REPOS" -r "$REV"
    backup_dir=/x1/svn/infra-backups.d/infra.$shard
    [ -d $backup_dir ] || mkdir $backup_dir
    $SVNADMIN dump --incremental -r "$REV" "$REPOS" | gzip > $backup_dir/infra.$REV.gz &

    # Send the commit mail
    $MAILER commit "$REPOS" "$REV" /x1/svn/asf-mailer.conf \
        2>>/var/log/svnmailer/errors/infra-mailer-stderr &

    # Sync the mirrors!
    $SETLOCK /var/tmp/infrasync.lock $SUDO -H -u svn $SVNSYNC sync --disable-locking --source-username=asf-sync-process --sync-username=asf-sync-process https://harmonia-2012.apache.org/repos/infra-proxy-sync 2>>/var/log/svninfrasynclog &
fi

# Trigger the SVN authz file to be rebuilt if the template file is modified
$SVNLOOK dirs-changed -r "$REV" "$REPOS" | grep -q "^infrastructure/trunk/subversion/authorization" \
 && $SUDO -H -u svn $SVN up /x1/svn/config/authorization \
 && $SUDO -H -u svn /x1/svn/scripts/authorization/gen_asf-authorization_on_template_commit.pl > /dev/null


#
if [ "$HOSTNAME" = "$MASTER_HOSTNAME" ] 
then
    export PYTHON_EGG_CACHE="/var/tmp/nobody_egg_cache"
    LC_ALL=en_US.UTF-8 $PUBSUB "$REPOS" "$REV" >>/var/log/svn_pubsub.log 2>&1 &
fi

# BuildBot Specific

if [ "$HOSTNAME" = "$MASTER_HOSTNAME" ] 
then
    $SVNLOOK dirs-changed -r "$REV" "$REPOS" | egrep -qf "$BUILDBOT_PROJECT_PATHS" && ( $BUILDBOT --repository "$REPOS" --revision "$REV" --bbserver ci.apache.org --bbport 9989 --project-paths "$BUILDBOT_PROJECT_PATHS" >>/var/log/svn_buildbot.log 2>&1 & )
fi
exit 0;

