#!/bin/sh

# PRE-LOCK HOOK
#
# The pre-lock hook is invoked before an exclusive lock is
# created.  Subversion runs this hook by invoking a program 
# (script, executable, binary, etc.) named 'pre-lock' (for which
# this file is a template), with the following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] PATH         (the path in the repository about to be locked)
#   [3] USER         (the user creating the lock)
#
# The default working directory for the invocation is undefined, so
# the program should set one explicitly if it cares.
#
# If the hook program exits with success, the lock is created; but
# if it exits with failure (non-zero), the lock action is aborted
# and STDERR is returned to the client.

# On a Unix system, the normal procedure is to have 'pre-lock'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that 'pre-lock' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# 'pre-lock.bat' or 'pre-lock.exe',
# but the basic idea is the same.
#
# Here is an example hook script, for a Unix /bin/sh interpreter:

REPOS="$1"
PATH="$2"
USER="$3"

# If a lock exists and is owned by a different person, don't allow it
# to be stolen (e.g., with 'svn lock --force ...').

# (Maybe this script could send email to the lock owner?)
SVNLOOK=/usr/bin/svnlook
GREP=/usr/bin/grep
SED=/usr/bin/sed

MIME_TYPE=`$SVNLOOK pg "$REPOS" svn:mime-type "$PATH" 2>/dev/null`
MAINTENANCE=/etc/nocommit

if [ -f $MAINTENANCE ]; then
  echo "Write access is currently disabled. The ASF SVN repository is currently undergoing maintenance."  > /dev/stderr
  exit 1
fi

# No MIME type, no lock.
if test -z "$MIME_TYPE"; then
  echo "Error: $PATH must have an appropriate MIME type to be locked." 1>&2
  exit 1
fi

# Disallow locking on text/ files.
TEXT_MIME_TYPE=`echo $MIME_TYPE | $GREP -v '^text/'`

if test -z "$TEXT_MIME_TYPE"; then
  echo "Error: $PATH has a text/ MIME type." 1>&2
  exit 2
fi

LOCK_OWNER=`$SVNLOOK lock "$REPOS" "$PATH" | \
            $GREP '^Owner: ' | $SED 's/Owner: //'`

# If we get no result from svnlook, there's no lock, allow the lock to
# happen:
if test -z "$LOCK_OWNER"; then
  exit 0
fi

# If the person locking matches the lock's owner, allow the lock to
# happen:
if test "$LOCK_OWNER" -eq "$USER"; then
  exit 0
fi

# Otherwise, we've got an owner mismatch, so return failure:
echo "Error: $PATH already locked by ${LOCK_OWNER}." 1>&2
exit 3
