#!/usr/local/bin/bash
#
# This pre-commit hook script makes sure that we're not committing a busted
# asf-authorizaton file, since if you commit a busted asf-authorization file
# you have to manually fix things on svn.apache.org before anyone can commit.
#
# Note that you need to compile and install svnauthz-validate manually to 
# get this to work, since it's built as part of 'make install-tools' in svn, not
# part of the traditional svn build.
#

MAINTENANCE=/etc/nocommit

if [ -f $MAINTENANCE ]; then
  echo "Write access is currently disabled. The ASF SVN repository is currently undergoing maintenance." > /dev/stderr
  exit 1
fi
source /x1/svn/hooks/pre-commit-sha1

exit 0
